name: Build GitBook
on:
  workflow_dispatch:
    inputs:
      repo:
        type: string

jobs:
  run:
    name: Convert Obsidian to GitBook
    runs-on: ubuntu-latest
    steps:
      - name: Print repo variable
        run: echo Repo variable is ${{ inputs.repo }}