name: Build GitBook
on:
  push
  workflow_dispatch:
    inputs:
      repo:
        default: ${{secrets.OBSIDIAN_REPO}}
        type: string

jobs:
  run:
    name: Convert Obsidian to GitBook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Clone Obsidian vault
        if: inputs.repo != null
        uses: actions/checkout@v2
        with:
          repository: ${{inputs.repo}}
          path: obsidian

      - name: Install dependencies
        working-directory: ./src
        run: npm install

      - name: Run the builder
        working-directory: ./src
        run: npm run build:gitbook

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: '🤖 Build for GitBook'
          add: 'gitbook'