name: Build GitBook
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository to use as Obsidian project'
        type: string

jobs:
  run:
    name: Convert Obsidian to GitBook
    runs-on: ubuntu-latest
    steps:
      - name: Print repo variable
        run: echo Repo variable is ${{ github.event.inputs.repo }}